version: 0.2

eb_codebuild_settings:
  CodeBuildServiceRole: arn:aws:iam::697877139013:role/service-role/code-build-BOAC-service-role
  ComputeType: BUILD_GENERAL1_MEDIUM
  Image: aws/codebuild/python:3.6.3
  Timeout: 60

phases:
  install:
    commands:
      - echo "install phase"
  pre_build:
    commands:
      - echo "pre_build phase"
  build:
    commands:
      - echo "build phase"
  post_build:
    commands:
      - echo "post_build phase"

artifacts:
  files:
  - '.bowerrc'
  - '.ebextensions/**/*'
  - 'app/**/*'
  - 'boac/**/*'
  - 'bower.json'
  - 'config/**/*'
  - 'fixtures/**/*'
  - 'package.json'
  - 'requirements.txt'
  - 'run.py'
  - 'scripts/**/*'
