version: 0.2

eb_codebuild_settings:
  CodeBuildServiceRole: arn:aws:iam::697877139013:role/service-role/code-build-boa-service-role
  ComputeType: BUILD_GENERAL1_MEDIUM
  Image: aws/codebuild/nodejs:8.11.0
  Timeout: 60

phases:
  install:
    commands:
      - npm -v
      - npm install

  pre_build:
    commands:
      - echo "pre_build phase"

  build:
    commands:
      - sudo npm install -g @vue/cli
      - sudo npm run build-vue
      - mv ./dist/static/vue/* ./dist/static/

  post_build:
    commands:
      - chmod 755 ./scripts/*.sh
      - ./scripts/create-build-summary.sh

artifacts:
  files:
  - '.ebextensions/**/*'
  - 'app/**/*'
  - 'boac/**/*'
  - 'config/**/*'
  - 'dist/**/*'
  - 'fixtures/**/*'
  - 'requirements.txt'
  - 'run.py'
  - 'scripts/**/*'
